import React, { useMemo, useCallback } from 'react';
import { assessmentCategories, frameworkTemplates, severityConfig } from '../data/assessmentData';

const ReviewStep = ({ config, responses }) => {
  const activeTemplate = frameworkTemplates.find(t => t.id === config.template) || frameworkTemplates[0];

  const filteredCategories = useMemo(() => {
    return assessmentCategories.map(cat => ({
      ...cat,
      items: cat.items.filter(activeTemplate.filter)
    })).filter(cat => cat.items.length > 0);
  }, [activeTemplate]);

  const stats = useMemo(() => {
    let totalItems = 0, pass = 0, fail = 0, partial = 0, na = 0, unassessed = 0;
    let totalWeight = 0, passedWeight = 0;

    filteredCategories.forEach(cat => {
      cat.items.forEach(item => {
        totalItems++;
        const resp = responses[item.id];
        const weight = severityConfig[item.severity]?.weight || 1;
        totalWeight += weight;

        if (!resp?.status || resp.status === '') { unassessed++; }
        else if (resp.status === 'pass') { pass++; passedWeight += weight; }
        else if (resp.status === 'fail') { fail++; }
        else if (resp.status === 'partial') { partial++; passedWeight += weight * 0.5; }
        else if (resp.status === 'na') { na++; totalWeight -= weight; }
      });
    });

    const score = totalWeight > 0 ? Math.round((passedWeight / totalWeight) * 100) : 0;
    return { totalItems, pass, fail, partial, na, unassessed, score };
  }, [filteredCategories, responses]);

  const getCategoryBreakdown = useCallback((cat) => {
    let pass = 0, fail = 0, partial = 0, na = 0;
    cat.items.forEach(item => {
      const s = responses[item.id]?.status;
      if (s === 'pass') pass++;
      else if (s === 'fail') fail++;
      else if (s === 'partial') partial++;
      else if (s === 'na') na++;
    });
    const total = cat.items.length;
    return { pass, fail, partial, na, total };
  }, [responses]);

  const barPcts = useMemo(() => {
    const total = stats.totalItems;
    if (total === 0) return { pass: 0, partial: 0, fail: 0, na: 0 };
    return {
      pass: (stats.pass / total) * 100,
      partial: (stats.partial / total) * 100,
      fail: (stats.fail / total) * 100,
      na: (stats.na / total) * 100,
    };
  }, [stats]);

  const generateMarkdown = () => {
    let md = `# DevOps/DevSecOps Security Assessment Report\n\n`;
    md += `| Field | Value |\n|-------|-------|\n`;
    md += `| Organization | ${config.orgName || 'N/A'} |\n`;
    md += `| Assessor | ${config.assessorName || 'N/A'} |\n`;
    md += `| Date | ${config.date || 'N/A'} |\n`;
    md += `| Environment | ${config.environment || 'N/A'} |\n`;
    md += `| Template | ${activeTemplate.name} |\n`;
    md += `| Overall Score | ${stats.score}% |\n\n`;

    if (config.scope) {
      md += `## Scope\n\n${config.scope}\n\n`;
    }

    md += `## Executive Summary\n\n`;
    md += `- **Total Controls Assessed:** ${stats.totalItems}\n`;
    md += `- **Pass:** ${stats.pass} | **Fail:** ${stats.fail} | **Partial:** ${stats.partial} | **N/A:** ${stats.na} | **Unassessed:** ${stats.unassessed}\n`;
    md += `- **Weighted Score:** ${stats.score}%\n\n`;

    md += `---\n\n`;

    filteredCategories.forEach(cat => {
      md += `## ${cat.icon} ${cat.title}\n\n`;
      md += `${cat.description}\n\n`;
      md += `| Status | Severity | Control | Notes |\n|--------|----------|---------|-------|\n`;

      cat.items.forEach(item => {
        const resp = responses[item.id] || {};
        const statusMap = { pass: '✅ Pass', fail: '❌ Fail', partial: '⚠️ Partial', na: '➖ N/A' };
        const status = statusMap[resp.status] || '⬜ Unassessed';
        const notes = (resp.notes || '—').replace(/\n/g, ' ');
        md += `| ${status} | ${item.severity.toUpperCase()} | ${item.text} | ${notes} |\n`;
      });

      md += `\n`;
    });

    // Findings section
    const failedItems = [];
    filteredCategories.forEach(cat => {
      cat.items.forEach(item => {
        const resp = responses[item.id];
        if (resp?.status === 'fail' || resp?.status === 'partial') {
          failedItems.push({ ...item, categoryTitle: cat.title, notes: resp.notes, status: resp.status });
        }
      });
    });

    if (failedItems.length > 0) {
      md += `---\n\n## 🚨 Findings & Remediation Required\n\n`;
      failedItems.forEach((item, idx) => {
        md += `### ${idx + 1}. ${item.text}\n\n`;
        md += `- **Category:** ${item.categoryTitle}\n`;
        md += `- **Severity:** ${item.severity.toUpperCase()}\n`;
        md += `- **Status:** ${item.status === 'fail' ? 'FAIL' : 'PARTIAL'}\n`;
        if (item.notes) md += `- **Notes:** ${item.notes}\n`;
        md += `\n`;
      });
    }

    md += `---\n\n*Generated by SecAssess — DevOps Assessment Generator*\n`;
    return md;
  };

  const generateJSON = () => {
    const report = {
      metadata: {
        organization: config.orgName,
        assessor: config.assessorName,
        date: config.date,
        environment: config.environment,
        template: activeTemplate.name,
        scope: config.scope,
        generatedAt: new Date().toISOString(),
      },
      summary: stats,
      categories: filteredCategories.map(cat => ({
        id: cat.id,
        title: cat.title,
        items: cat.items.map(item => ({
          id: item.id,
          control: item.text,
          severity: item.severity,
          tags: item.tags,
          status: responses[item.id]?.status || 'unassessed',
          notes: responses[item.id]?.notes || '',
        }))
      }))
    };
    return JSON.stringify(report, null, 2);
  };

  const generateHTML = () => {
    const failedItems = [];
    filteredCategories.forEach(cat => {
      cat.items.forEach(item => {
        const resp = responses[item.id];
        if (resp?.status === 'fail' || resp?.status === 'partial') {
          failedItems.push({ ...item, categoryTitle: cat.title, notes: resp.notes, status: resp.status });
        }
      });
    });

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Assessment Report — ${config.orgName || 'DevOps Assessment'}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background:#0a0a14; color:#e0dff0; line-height:1.6; padding:40px; }
  .container { max-width:900px; margin:0 auto; }
  h1 { font-size:28px; margin-bottom:8px; color:#fff; }
  h2 { font-size:20px; margin:28px 0 12px; color:#a29bfe; border-bottom:1px solid rgba(108,92,231,0.2); padding-bottom:8px; }
  h3 { font-size:16px; margin:16px 0 8px; }
  .meta { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin:20px 0 30px; }
  .meta-item { background:#12122a; padding:14px; border-radius:8px; border:1px solid rgba(108,92,231,0.15); }
  .meta-label { font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#6b6890; }
  .meta-value { font-size:15px; color:#e0dff0; margin-top:4px; }
  .summary-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:16px 0 28px; }
  .stat-card { background:#12122a; padding:18px; border-radius:8px; text-align:center; border:1px solid rgba(108,92,231,0.15); }
  .stat-value { font-size:32px; font-weight:700; }
  .stat-value.score { color:#6c5ce7; }
  .stat-value.pass { color:#00cec9; }
  .stat-value.fail { color:#ff3b5c; }
  .stat-label { font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#6b6890; margin-top:4px; }
  table { width:100%; border-collapse:collapse; margin:12px 0 24px; }
  th { background:#16163a; padding:10px 12px; text-align:left; font-size:12px; text-transform:uppercase; letter-spacing:0.5px; color:#8b88a2; border-bottom:2px solid rgba(108,92,231,0.2); }
  td { padding:10px 12px; border-bottom:1px solid rgba(108,92,231,0.08); font-size:13px; vertical-align:top; }
  tr:hover td { background:rgba(108,92,231,0.03); }
  .badge { display:inline-block; padding:2px 8px; border-radius:12px; font-size:10px; font-weight:600; text-transform:uppercase; letter-spacing:0.5px; }
  .badge.pass { background:rgba(0,206,201,0.15); color:#00cec9; }
  .badge.fail { background:rgba(255,59,92,0.15); color:#ff3b5c; }
  .badge.partial { background:rgba(255,209,102,0.15); color:#ffd166; }
  .badge.na { background:rgba(90,87,117,0.15); color:#5a5775; }
  .badge.unassessed { background:rgba(90,87,117,0.1); color:#5a5775; }
  .badge.critical { background:rgba(255,59,92,0.12); color:#ff3b5c; }
  .badge.high { background:rgba(255,140,66,0.12); color:#ff8c42; }
  .badge.medium { background:rgba(255,209,102,0.12); color:#ffd166; }
  .badge.low { background:rgba(102,217,194,0.12); color:#66d9c2; }
  .finding { background:#12122a; border:1px solid rgba(255,59,92,0.2); border-radius:8px; padding:16px; margin:12px 0; }
  .finding h3 { color:#ff8c42; }
  .footer { margin-top:40px; text-align:center; color:#5a5775; font-size:12px; border-top:1px solid rgba(108,92,231,0.1); padding-top:16px; }
  @media print { body { background:white; color:#222; } .meta-item,.stat-card,.finding { border:1px solid #ddd; background:#f9f9f9; } th { background:#eee; color:#333; } }
</style>
</head>
<body>
<div class="container">
<h1>🛡️ DevOps / DevSecOps Security Assessment</h1>
<p style="color:#8b88a2;margin-bottom:8px;">Generated by SecAssess</p>

<div class="meta">
  <div class="meta-item"><div class="meta-label">Organization</div><div class="meta-value">${config.orgName || 'N/A'}</div></div>
  <div class="meta-item"><div class="meta-label">Assessor</div><div class="meta-value">${config.assessorName || 'N/A'}</div></div>
  <div class="meta-item"><div class="meta-label">Date</div><div class="meta-value">${config.date || 'N/A'}</div></div>
  <div class="meta-item"><div class="meta-label">Environment</div><div class="meta-value">${config.environment || 'N/A'}</div></div>
  <div class="meta-item"><div class="meta-label">Template</div><div class="meta-value">${activeTemplate.name}</div></div>
  <div class="meta-item"><div class="meta-label">Scope</div><div class="meta-value">${config.scope || 'N/A'}</div></div>
</div>

<h2>Executive Summary</h2>
<div class="summary-grid">
  <div class="stat-card"><div class="stat-value score">${stats.score}%</div><div class="stat-label">Overall Score</div></div>
  <div class="stat-card"><div class="stat-value pass">${stats.pass}</div><div class="stat-label">Passed</div></div>
  <div class="stat-card"><div class="stat-value fail">${stats.fail}</div><div class="stat-label">Failed</div></div>
  <div class="stat-card"><div class="stat-value">${stats.totalItems}</div><div class="stat-label">Total Controls</div></div>
</div>

${filteredCategories.map(cat => `
<h2>${cat.icon} ${cat.title}</h2>
<p style="color:#8b88a2;font-size:13px;margin-bottom:8px;">${cat.description}</p>
<table>
<thead><tr><th style="width:90px">Status</th><th style="width:80px">Severity</th><th>Control</th><th>Notes</th></tr></thead>
<tbody>
${cat.items.map(item => {
  const resp = responses[item.id] || {};
  const statusLabels = { pass:'Pass', fail:'Fail', partial:'Partial', na:'N/A' };
  const s = resp.status || 'unassessed';
  return `<tr>
    <td><span class="badge ${s}">${statusLabels[s] || 'Unassessed'}</span></td>
    <td><span class="badge ${item.severity}">${item.severity}</span></td>
    <td>${item.text}</td>
    <td style="color:#8b88a2">${resp.notes || '—'}</td>
  </tr>`;
}).join('')}
</tbody>
</table>
`).join('')}

${failedItems.length > 0 ? `
<h2>🚨 Findings Requiring Remediation</h2>
${failedItems.map((item, i) => `
<div class="finding">
  <h3>${i+1}. ${item.text}</h3>
  <p><strong>Category:</strong> ${item.categoryTitle} &nbsp;|&nbsp; <strong>Severity:</strong> <span class="badge ${item.severity}">${item.severity}</span> &nbsp;|&nbsp; <strong>Status:</strong> <span class="badge ${item.status}">${item.status === 'fail' ? 'Fail' : 'Partial'}</span></p>
  ${item.notes ? `<p style="margin-top:8px;color:#bbb;">${item.notes}</p>` : ''}
</div>
`).join('')}
` : ''}

<div class="footer">SecAssess — DevOps & DevSecOps Assessment Generator &nbsp;•&nbsp; ${new Date().toLocaleDateString()}</div>
</div>
</body>
</html>`;
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportMarkdown = () => {
    downloadFile(generateMarkdown(), `assessment-${config.orgName || 'report'}-${config.date || 'undated'}.md`, 'text/markdown');
  };

  const exportJSON = () => {
    downloadFile(generateJSON(), `assessment-${config.orgName || 'report'}-${config.date || 'undated'}.json`, 'application/json');
  };

  const exportHTML = () => {
    downloadFile(generateHTML(), `assessment-${config.orgName || 'report'}-${config.date || 'undated'}.html`, 'text/html');
  };

  return (
    <div className="animate-in">
      <div className="section-header">
        <h2>Review & Export</h2>
        <p>Review your assessment results and export the final document.</p>
      </div>

      <div className="review-summary">
        <div className="summary-card score animate-in stagger-1">
          <div className="summary-value">{stats.score}%</div>
          <div className="summary-label">Overall Score</div>
        </div>
        <div className="summary-card pass animate-in stagger-2">
          <div className="summary-value">{stats.pass}</div>
          <div className="summary-label">Passed</div>
        </div>
        <div className="summary-card fail animate-in stagger-3">
          <div className="summary-value">{stats.fail}</div>
          <div className="summary-label">Failed</div>
        </div>
        <div className="summary-card items animate-in stagger-4">
          <div className="summary-value">{stats.totalItems}</div>
          <div className="summary-label">Total Controls</div>
        </div>
      </div>

      <div className="score-bar-container">
        <h4>Assessment Distribution</h4>
        <div className="score-bar">
          <div className="score-bar-segment pass" style={{ width: `${barPcts.pass}%` }} />
          <div className="score-bar-segment partial" style={{ width: `${barPcts.partial}%` }} />
          <div className="score-bar-segment fail" style={{ width: `${barPcts.fail}%` }} />
          <div className="score-bar-segment na" style={{ width: `${barPcts.na}%` }} />
        </div>
        <div className="score-legend">
          <div className="score-legend-item"><div className="score-legend-dot" style={{ background: 'var(--accent-secondary)' }} /> Pass ({stats.pass})</div>
          <div className="score-legend-item"><div className="score-legend-dot" style={{ background: 'var(--severity-medium)' }} /> Partial ({stats.partial})</div>
          <div className="score-legend-item"><div className="score-legend-dot" style={{ background: 'var(--severity-critical)' }} /> Fail ({stats.fail})</div>
          <div className="score-legend-item"><div className="score-legend-dot" style={{ background: 'var(--text-muted)', opacity: 0.5 }} /> N/A ({stats.na})</div>
          <div className="score-legend-item"><div className="score-legend-dot" style={{ background: 'var(--bg-elevated)' }} /> Unassessed ({stats.unassessed})</div>
        </div>
      </div>

      <div className="section-header">
        <h2>Category Breakdown</h2>
      </div>

      <div className="breakdown-grid">
        {filteredCategories.map(cat => {
          const bd = getCategoryBreakdown(cat);
          const total = bd.total;
          return (
            <div key={cat.id} className="breakdown-card">
              <h4>{cat.icon} {cat.title}</h4>
              <div className="breakdown-mini-bar">
                <div className="score-bar-segment pass" style={{ width: `${(bd.pass / total) * 100}%` }} />
                <div className="score-bar-segment partial" style={{ width: `${(bd.partial / total) * 100}%` }} />
                <div className="score-bar-segment fail" style={{ width: `${(bd.fail / total) * 100}%` }} />
              </div>
              <div className="breakdown-stats">
                <span style={{ color: 'var(--accent-secondary)' }}>✓ {bd.pass}</span>
                <span style={{ color: 'var(--severity-medium)' }}>◐ {bd.partial}</span>
                <span style={{ color: 'var(--severity-critical)' }}>✗ {bd.fail}</span>
                <span style={{ color: 'var(--text-muted)' }}>— {bd.na}</span>
              </div>
            </div>
          );
        })}
      </div>

      <div className="section-header">
        <h2>Export Assessment</h2>
        <p>Download your completed assessment in your preferred format.</p>
      </div>

      <div className="export-options">
        <div className="export-option" onClick={exportHTML}>
          <div className="export-icon">🌐</div>
          <h4>HTML Report</h4>
          <p>Styled, printable document</p>
        </div>
        <div className="export-option" onClick={exportMarkdown}>
          <div className="export-icon">📝</div>
          <h4>Markdown</h4>
          <p>For docs, wikis, and Git</p>
        </div>
        <div className="export-option" onClick={exportJSON}>
          <div className="export-icon">📦</div>
          <h4>JSON Data</h4>
          <p>Structured data for automation</p>
        </div>
      </div>
    </div>
  );
};

export default ReviewStep;
